CoreDomain\Model\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
            groups:
                - api_user_get
        email:
            expose: true
            type: string
            groups:
                - api_user_get
        roles:
            expose: true
            type: array
            groups:
                - api_user_get
