parameters:
#    parameter_name: value

services:
    ### Services
    app.security.api_user_provider:
        class: AppBundle\Security\User\ApiUserProvider
        arguments:
            - @app.repository.user

    app.security.api_token_authenticator:
        class: AppBundle\Security\Authentication\ApiTokenAuthenticator
        arguments: [@app.security.api_user_provider]

    app.security.user_password_encoder:
        class: AppBundle\Security\User\UserPasswordEncoder
        arguments: [@security.encoder_factory.generic, "CoreDomain\\Model\\User"]

    app.command_handler:
        class: CoreDomain\Handler\CommandHandler

    app.messenger:
        class: AppBundle\Infrastructure\Mail\Messenger
        arguments:
            - @mailer
            - @templating
            - @translator
            - %mailer_from%

    ### Repository
    app.repository.user:
        class: AppBundle\Repository\UserRepository
        arguments: [@doctrine.orm.default_entity_manager]

    app.repository.user_session:
        class: AppBundle\Repository\UserSessionRepository
        arguments: [@doctrine.orm.default_entity_manager]

    ### Commands
    app.command.add_user:
        class: CoreDomain\Command\User\AddUserCommand
        arguments: [@app.repository.user, @app.security.user_password_encoder, @validator]

    app.command.add_session:
        class: CoreDomain\Command\User\AddSessionCommand
        arguments: [@app.repository.user, @app.repository.user_session, @app.security.user_password_encoder]

    app.command.reset_password_user:
        class: CoreDomain\Command\User\ResetPasswordCommand
        arguments: [@app.repository.user, @app.security.user_password_encoder, @app.messenger]

    app.command.update_profile_user:
        class: CoreDomain\Command\User\UpdateProfileCommand
        arguments: [@app.repository.user, @app.security.user_password_encoder, @validator]

    ### Listeners
    app.domain.exception.listener:
        class: AppBundle\Listener\DomainExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onDomainException }

    app.mailer.queue.listener:
        class: AppBundle\Listener\MailerQueueListener
        arguments:
            - @app.messenger
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }
