CoreDomain\DTO\ProfileDTO:
    exclusion_policy: ALL
    properties:
        password:
            expose: true
            type: string
            groups: [api_user_patch]
        fullName:
            expose: true
            serialized_name: fullName
            type: string
            groups: [api_user_patch]
        phone:
            expose: true
            type: string
            groups: [api_user_patch]