---
# application tasks to be customized and to run after the main provision

- name: install vendors
  composer: command=install working_dir=/vagrant no_dev=no

- name: install node packages
  shell: npm install chdir=/vagrant
  sudo: true

- name: install jspm packages
  shell: jspm install chdir=/vagrant
  sudo: true

#- name: build frontend
#  shell: gulp build chdir=/vagrant