CoreDomain\Model\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        email:
            type: string
            unique: true
        password:
            type: string
        salt:
            type: string
            nullable: false
        roles:
            type: array
        fullName:
            type: string
            nullable: true
        phone:
            type: string
            nullable: true

    oneToMany:
        sessions:
            targetEntity: CoreDomain\Model\UserSession
            mappedBy: user