CoreDomain\Model\UserSession:
    type: entity
    table: user_session
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        token:
            type: string
            length: 255
            unique: true
        createdAt:
            column: created_at
            type: datetime
            nullable: false
    manyToOne:
        user:
            targetEntity: CoreDomain\Model\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE