CoreDomain\DTO\UserDTO:
    properties:
        email:
            - Email:
                groups: [api_user_post, api_session_post]
            - NotBlank:
                groups: [api_user_post, api_session_post]
        password:
            - NotBlank:
                groups: [api_user_post, api_session_post]
            - Length:
                min: 6
                groups: [api_user_post, api_session_post]