---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - nodejs
    - maildev
    - vagrant_local
    - apache
#    - galaxy/Mayeu.RabbitMQ
    - galaxy/ANXS.postgresql
    - php
    - xdebug
    - composer
    - app
